### ISSUE TITLE
Specify a reference job for timing data

### ISSUE THREAD

**Issue by krishnawhite** [jenkinsci/parallel-test-executor-plugin#132]
When a new Jenkins job is created in order to run tests against a feature branch, the first test run against that branch is always extremely slow. 

Because there are no previous builds from which to gather timing data, everything runs in serial on a single node.

It should be possible to specify a reference job (eg master), so that test runs against short-lived feature branches take their timing data from the reference job instead of running everything in serial the first time round.

The very reason for this plugin's existence is to parallelise test runs that would otherwise take a very long time to run in serial. It is therefore very unsatisfying that when a new job is created to run tests against a branch (a common use case), the benefits of this plugin are entirely lost and users must wait hours or days for the initial run to complete.

A number of other users have made the same or similar requests in the past (eg https://issues.jenkins-ci.org/browse/JENKINS-33169 and https://issues.jenkins-ci.org/browse/JENKINS-22896), so I believe this is a problem affecting many people. 

Previous users who requested this feature were pointed towards https://issues.jenkins-ci.org/browse/JENKINS-33274 as a possible resolution, but this work since was abandoned in 2017.

Please can we have some means of dealing with this problem?

**Comment by imavroukakis** [comment]
Hi @krishnawhite , have you tried using `estimateTestsFromFiles` ?

**Comment by krishnawhite** [comment]
Hey @imavroukakis thanks for this, I wasn't aware of that feature.

Unfortunately it doesn't work for me because I'm using this plugin to run Python tests, and it seems to only detect Java classes, but for others using this with Java it looks like it would solve this problem.
