### ISSUE TITLE
Provide example with declarative pipelines

### ISSUE THREAD

**Issue by mildred** [jenkinsci/parallel-test-executor-plugin#28]
There are [examples on how to use this plugin with scripted pipelines](https://jenkins.io/blog/2016/06/16/parallel-test-executor-plugin/), but how do you use it with declarative pipelines?

Thanks

**Comment by jglick** [comment]
I do not think it is possible.

BTW please use the users’ list, IRC #jenkins, stackoverflow.com, etc. for questions.

**Comment by ChristianCiach** [comment]
> I do not think it is possible.

Is this still accurate? I don't see why it shouldn't be possible to offer a declarative pipeline command that covers common use cases of this plugin.

I would rather not rewrite our easily readable declarative pipeline as a scripted pipeline just to be able to use this plugin.
